options(repos="http://cran.univ-lyon1.fr/")
f <- sprintf("%s.R",tempfile())
cat("x <- 5\n",file=f)
unlink("anRpackage",recursive=TRUE)
package.skeleton(code_files=f)
install.packages("inlinedocs")
library(inlinedocs)
package.skeleton.dx("anRpackage")
unlink("anRpackage",recursive=TRUE)
package.skeleton(code_files=f)
sessionInfo()
